# Site settings
title: Lockstep Labs
email: info@locksteplabs.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Lockstep! We build high-impact, modern web and mobile applications.
  Have an idea for a new technology? Need to scale your team? Look no further!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locksteplabs.com" # the base hostname & protocol for your site
twitter_username: locksteplabs
github_username:  lockstep

# Build settings
markdown: kramdown
